import type { AppData } from "./types";

export const SEED_VERSION = 1;

const T = {
  kumoCreated: "2026-08-12T14:00:00.000Z",
  contract: "2026-08-14T16:20:00.000Z",
  published: "2026-08-26T18:10:00.000Z",
  c1: "2026-08-28T09:12:00.000Z",
  c2: "2026-08-28T09:18:00.000Z",
  c3: "2026-08-28T11:04:00.000Z",
  c4: "2026-08-28T11:22:00.000Z",
  c5: "2026-08-28T15:41:00.000Z",
  c6: "2026-08-28T16:02:00.000Z",
  c7: "2026-08-28T16:08:00.000Z",
  due: "2026-08-30T17:00:00.000Z",
  harbor: "2026-08-20T13:00:00.000Z",
  solstice: "2026-07-02T10:00:00.000Z",
  solsticeDone: "2026-08-08T15:00:00.000Z",
};

export function createSeed(): AppData {
  return {
    seedVersion: SEED_VERSION,
    workspace: {
      id: "ws-hearth",
      name: "Hearth Studio",
      slug: "hearth",
      leadName: "Avery Lin",
      leadTitle: "Creative director",
      brandColor: "#1F3D34",
    },
    clients: [
      {
        id: "client-kumo",
        name: "Kumo Coffee",
        description: "A quiet neighborhood coffee and kitchen opening this autumn.",
        industry: "Hospitality",
        status: "active",
        createdAt: T.kumoCreated,
      },
      {
        id: "client-harbor",
        name: "Harbor Press",
        description: "Independent publisher of long-form essays and seasonal catalogs.",
        industry: "Publishing",
        status: "active",
        createdAt: T.harbor,
      },
      {
        id: "client-solstice",
        name: "Solstice Goods",
        description: "Small-batch body care. Packaging system delivered in August.",
        industry: "CPG",
        status: "active",
        createdAt: T.solstice,
      },
    ],
    contacts: [
      {
        id: "contact-maya",
        clientId: "client-kumo",
        name: "Maya Chen",
        email: "maya@kumocoffee.com",
        title: "Marketing lead",
        isDefaultApprover: true,
      },
      {
        id: "contact-tom",
        clientId: "client-kumo",
        name: "Tom Walsh",
        email: "tom@kumocoffee.com",
        title: "Founder",
        isDefaultApprover: false,
      },
      {
        id: "contact-priya",
        clientId: "client-kumo",
        name: "Priya Shah",
        email: "priya@kumocoffee.com",
        title: "Operations",
        isDefaultApprover: false,
      },
      {
        id: "contact-elena",
        clientId: "client-harbor",
        name: "Elena Voss",
        email: "elena@harborpress.com",
        title: "Editor-in-chief",
        isDefaultApprover: true,
      },
      {
        id: "contact-jonah",
        clientId: "client-solstice",
        name: "Jonah Reed",
        email: "jonah@solsticegoods.com",
        title: "Founder",
        isDefaultApprover: true,
      },
    ],
    projects: [
      {
        id: "project-kumo",
        clientId: "client-kumo",
        name: "Brand launch",
        projectType: "Brand identity",
        state: "active",
        leadName: "Avery Lin",
        targetDate: "2026-09-18",
        revisionAllowance: 2,
        revisionUsed: 0,
        currentContractId: "contract-kumo-v1",
        createdAt: T.kumoCreated,
      },
      {
        id: "project-harbor",
        clientId: "client-harbor",
        name: "Autumn catalog",
        projectType: "Editorial",
        state: "aligned",
        leadName: "Avery Lin",
        targetDate: "2026-09-30",
        revisionAllowance: 2,
        revisionUsed: 0,
        currentContractId: "contract-harbor-v1",
        createdAt: T.harbor,
      },
      {
        id: "project-solstice",
        clientId: "client-solstice",
        name: "Packaging system",
        projectType: "Packaging",
        state: "delivered",
        leadName: "Sam Okonkwo",
        targetDate: "2026-08-08",
        revisionAllowance: 2,
        revisionUsed: 1,
        currentContractId: "contract-solstice-v1",
        createdAt: T.solstice,
      },
    ],
    contracts: [
      {
        id: "contract-kumo-v1",
        projectId: "project-kumo",
        versionNumber: 1,
        status: "approved",
        objective:
          "Launch a complete visual identity for Kumo Coffee so the shop can open this autumn with a calm, contemporary presence across signage, print, and social.",
        audience:
          "Neighborhood regulars and design-aware visitors in their 20s–40s who want a quiet place to sit, not a spectacle.",
        thesis:
          "Quiet, warm, precise, contemporary. The brand should feel like morning light on linen — generous, unhurried, and exact.",
        principles: [
          "Warm cream, umber, charcoal, and muted sage. Neutral palette is a hard constraint.",
          "Serif wordmark with a thin steam-arc mark. Generous whitespace.",
          "Photography: window light, ceramic, linen. No people as heroes in V1.",
          "One idea per surface. Do not decorate.",
        ],
        avoid: [
          "Generic Japanese clichés (red sun, torii, waves, cherry blossom scatter)",
          "Anime or illustrated mascots",
          "Overly rustic chalkboard / barn-wood cafe tropes",
          "Bright red, neon, or high-chroma ‘pop’ colors",
        ],
        deliverablesSummary: [
          "Primary identity (wordmark + mark, two concepts for round 1)",
          "Launch poster",
          "Five social templates",
          "Menu cover",
        ],
        inScope: [
          "Static identity, poster, social templates, menu cover",
          "Two included revision rounds after first review",
        ],
        outOfScope: [
          "Motion / animated stories",
          "Interior signage fabrication",
          "Website build",
          "Packaging for retail beans (later phase)",
        ],
        constraints: [
          "Final approval: Maya Chen, marketing lead",
          "Must work in one-color print and full color",
          "Social templates sized for Instagram 1:1",
        ],
        inputs: [
          "Verbal brief from Maya and Tom, 12 Aug",
          "Reference interiors (oak, plaster, stoneware)",
        ],
        missing: ["Exact opening date for poster copy", "Final menu item list"],
        approverName: "Maya Chen",
        revisionAllowance: 2,
        approvedBy: "Avery Lin",
        approvedAt: T.contract,
        createdAt: T.kumoCreated,
      },
      {
        id: "contract-harbor-v1",
        projectId: "project-harbor",
        versionNumber: 1,
        status: "approved",
        objective:
          "Design the Autumn 2026 catalog cover and interior chapter openers for Harbor Press.",
        audience: "Existing subscribers and independent bookshop buyers.",
        thesis: "Literary, tactile, unhurried. Paper as a material, not a texture filter.",
        principles: ["Letterpress-informed type", "Restrained photography", "No seasonal cliché foliage dumps"],
        avoid: ["Stock autumn leaves", "Distressed vintage filters"],
        deliverablesSummary: ["Catalog cover", "Six chapter openers", "Social announcement card"],
        inScope: ["Print-ready cover and openers", "One social card"],
        outOfScope: ["Full interior typesetting", "Print production management"],
        constraints: ["Trim 8.5 × 11", "Two-color plus black"],
        inputs: ["Essay list from Elena"],
        missing: ["Final essay titles for two chapters"],
        approverName: "Elena Voss",
        revisionAllowance: 2,
        approvedBy: "Avery Lin",
        approvedAt: T.harbor,
        createdAt: T.harbor,
      },
      {
        id: "contract-solstice-v1",
        projectId: "project-solstice",
        versionNumber: 1,
        status: "approved",
        objective: "A packaging system for four body-care SKUs.",
        audience: "Independent retailers and direct-to-consumer.",
        thesis: "Mineral, daylight, no spa cliché.",
        principles: ["One type family", "Uncoated stock"],
        avoid: ["Gold foil", "Script fonts", "Leaf illustrations"],
        deliverablesSummary: ["Primary packaging", "Shipping sleeve", "Label set"],
        inScope: ["Print-ready dielines"],
        outOfScope: ["Photography of product in use"],
        constraints: ["Must pass retailer barcode quiet zone"],
        inputs: ["Ingredient lists"],
        missing: [],
        approverName: "Jonah Reed",
        revisionAllowance: 2,
        approvedBy: "Avery Lin",
        approvedAt: T.solstice,
        createdAt: T.solstice,
      },
    ],
    deliverables: [
      {
        id: "del-identity",
        projectId: "project-kumo",
        name: "Primary identity",
        category: "Identity",
        description: "Wordmark, mark, and lockup. Round 1 presents two concepts.",
        scopeText: "Primary lockup in one-color and full color. No secondary illustration system in this round.",
        requirements: "PNG review rendition, square or 4:3. Vector source stays in studio files.",
        state: "in_review",
        ownerName: "Avery Lin",
        dueDate: "2026-08-26",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: "ver-identity-b",
      },
      {
        id: "del-poster",
        projectId: "project-kumo",
        name: "Launch poster",
        category: "Print",
        description: "Opening announcement poster for window and neighborhood flyposting.",
        scopeText: "Single static poster. Copy: Quiet coffee. Opening this autumn.",
        requirements: "Portrait print rendition. Final 18×24 later.",
        state: "in_review",
        ownerName: "Sam Okonkwo",
        dueDate: "2026-08-26",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: "ver-poster-v1",
      },
      {
        id: "del-social",
        projectId: "project-kumo",
        name: "Social templates",
        category: "Social",
        description: "Five 1:1 templates for launch week.",
        scopeText: "Static templates only. Motion is out of scope.",
        requirements: "1:1 JPG/PNG review renditions.",
        state: "in_review",
        ownerName: "Sam Okonkwo",
        dueDate: "2026-08-26",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: "ver-social-01",
      },
      {
        id: "del-menu",
        projectId: "project-kumo",
        name: "Menu cover",
        category: "Print",
        description: "Cover for the opening menu. Interior list is a later phase.",
        scopeText: "Cover only. Interior typesetting excluded.",
        requirements: "Portrait cover rendition.",
        state: "in_review",
        ownerName: "Avery Lin",
        dueDate: "2026-08-26",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: "ver-menu-v1",
      },
      {
        id: "del-harbor-cover",
        projectId: "project-harbor",
        name: "Catalog cover",
        category: "Print",
        description: "Autumn 2026 catalog cover.",
        scopeText: "Front cover plus spine.",
        requirements: "Print-ready PDF later; review as PNG.",
        state: "planned",
        ownerName: "Avery Lin",
        dueDate: "2026-09-12",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: null,
      },
      {
        id: "del-harbor-openers",
        projectId: "project-harbor",
        name: "Chapter openers",
        category: "Editorial",
        description: "Six interior chapter opener spreads.",
        scopeText: "Openers only, not full interior.",
        requirements: "Spread PNGs for review.",
        state: "planned",
        ownerName: "Sam Okonkwo",
        dueDate: "2026-09-20",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: null,
      },
      {
        id: "del-solstice-pack",
        projectId: "project-solstice",
        name: "Primary packaging",
        category: "Packaging",
        description: "Four SKU labels and outer carton.",
        scopeText: "Print-ready dielines.",
        requirements: "PDF + PNG.",
        state: "delivered",
        ownerName: "Sam Okonkwo",
        dueDate: "2026-08-08",
        isRequired: true,
        externalDependency: "none",
        externalNote: null,
        currentVersionId: "ver-solstice-v2",
      },
    ],
    versions: [
      {
        id: "ver-identity-a",
        deliverableId: "del-identity",
        projectId: "project-kumo",
        versionNumber: 1,
        name: "Concept A — geometric",
        imageUrl: "/kumo/identity-a.jpg",
        mimeType: "image/jpeg",
        width: 1600,
        height: 1200,
        byteSize: 616874,
        checksum: "a1c4e8f0",
        createdAt: "2026-08-25T20:00:00.000Z",
        note: "Condensed grotesque, overlapping-circle mark.",
      },
      {
        id: "ver-identity-b",
        deliverableId: "del-identity",
        projectId: "project-kumo",
        versionNumber: 2,
        name: "Concept B — serif steam",
        imageUrl: "/kumo/identity-b.jpg",
        mimeType: "image/jpeg",
        width: 1600,
        height: 1200,
        byteSize: 521752,
        checksum: "b29d11aa",
        createdAt: "2026-08-25T20:04:00.000Z",
        note: "Recommended direction. Serif wordmark, steam-arc mark.",
      },
      {
        id: "ver-poster-v1",
        deliverableId: "del-poster",
        projectId: "project-kumo",
        versionNumber: 1,
        name: "Poster v1",
        imageUrl: "/kumo/poster.jpg",
        mimeType: "image/jpeg",
        width: 1152,
        height: 1728,
        byteSize: 801718,
        checksum: "c7e20b14",
        createdAt: "2026-08-25T21:10:00.000Z",
        note: "Window-light cup, charcoal wordmark.",
      },
      {
        id: "ver-social-01",
        deliverableId: "del-social",
        projectId: "project-kumo",
        versionNumber: 1,
        name: "Social — morning still",
        imageUrl: "/kumo/social-01.jpg",
        mimeType: "image/jpeg",
        width: 1408,
        height: 1408,
        byteSize: 565053,
        checksum: "d4aa9012",
        createdAt: "2026-08-25T21:40:00.000Z",
        note: "Template 1 of 5.",
      },
      {
        id: "ver-social-02",
        deliverableId: "del-social",
        projectId: "project-kumo",
        versionNumber: 2,
        name: "Social — stay longer",
        imageUrl: "/kumo/social-02.jpg",
        mimeType: "image/jpeg",
        width: 1408,
        height: 1408,
        byteSize: 480000,
        checksum: "e81bb203",
        createdAt: "2026-08-25T21:42:00.000Z",
        note: "Template 2 of 5. Typographic.",
      },
      {
        id: "ver-social-03",
        deliverableId: "del-social",
        projectId: "project-kumo",
        versionNumber: 3,
        name: "Social — pastry",
        imageUrl: "/kumo/social-03.jpg",
        mimeType: "image/jpeg",
        width: 1408,
        height: 1408,
        byteSize: 510000,
        checksum: "f02cc394",
        createdAt: "2026-08-25T21:44:00.000Z",
        note: "Template 3 of 5.",
      },
      {
        id: "ver-menu-v1",
        deliverableId: "del-menu",
        projectId: "project-kumo",
        versionNumber: 1,
        name: "Menu cover v1",
        imageUrl: "/kumo/menu.jpg",
        mimeType: "image/jpeg",
        width: 1200,
        height: 1600,
        byteSize: 479839,
        checksum: "aa19d4c5",
        createdAt: "2026-08-25T22:00:00.000Z",
        note: "Cover only.",
      },
      {
        id: "ver-solstice-v2",
        deliverableId: "del-solstice-pack",
        projectId: "project-solstice",
        versionNumber: 2,
        name: "Packaging v2 — approved",
        imageUrl: "/kumo/social-03.jpg",
        mimeType: "image/jpeg",
        width: 1408,
        height: 1408,
        byteSize: 510000,
        checksum: "s0lst1ce",
        createdAt: T.solsticeDone,
        note: "Final approved rendition (placeholder in this demo).",
      },
    ],
    reviews: [
      {
        id: "round-kumo-1",
        projectId: "project-kumo",
        roundNumber: 1,
        title: "Round 1 — direction",
        contextText:
          "Two identity concepts, the launch poster, three of five social templates, and the menu cover. We recommend Concept B. Please tell us which identity to take forward, and anything that must change before round 2.",
        state: "feedback_open",
        dueAt: T.due,
        publishedAt: T.published,
        approverContactId: "contact-maya",
        guestToken: "kumo-r1",
        cancelledReason: null,
      },
    ],
    reviewItems: [
      {
        id: "ri-id-a",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-identity",
        assetVersionId: "ver-identity-a",
        displayOrder: 1,
        promptText: "Concept A. Geometric mark, condensed grotesque.",
      },
      {
        id: "ri-id-b",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-identity",
        assetVersionId: "ver-identity-b",
        displayOrder: 2,
        promptText: "Concept B (recommended). Serif wordmark, steam-arc mark.",
      },
      {
        id: "ri-poster",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-poster",
        assetVersionId: "ver-poster-v1",
        displayOrder: 3,
        promptText: "Does the poster feel like the shop you want to open?",
      },
      {
        id: "ri-social-1",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-social",
        assetVersionId: "ver-social-01",
        displayOrder: 4,
        promptText: "Social template 1 of 5 — still life.",
      },
      {
        id: "ri-social-2",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-social",
        assetVersionId: "ver-social-02",
        displayOrder: 5,
        promptText: "Social template 2 of 5 — typographic.",
      },
      {
        id: "ri-menu",
        reviewRoundId: "round-kumo-1",
        deliverableId: "del-menu",
        assetVersionId: "ver-menu-v1",
        displayOrder: 6,
        promptText: "Menu cover. Interior list comes later.",
      },
    ],
    sources: [
      {
        id: "src-1",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "general_comment",
        authorName: "Maya Chen",
        authorRole: "client",
        assetVersionId: "ver-identity-b",
        pageNumber: null,
        x: null,
        y: null,
        rawText: "We like concept B. The serif feels like us — quiet, not trying too hard.",
        sourceLabel: "Review comment",
        createdAt: T.c1,
      },
      {
        id: "src-2",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "pin_comment",
        authorName: "Maya Chen",
        authorRole: "client",
        assetVersionId: "ver-poster-v1",
        pageNumber: 1,
        x: 0.5,
        y: 0.18,
        rawText: "Can it feel warmer but not childish? The type is a little severe up here.",
        sourceLabel: "Pin on poster",
        createdAt: T.c2,
      },
      {
        id: "src-3",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "general_comment",
        authorName: "Tom Walsh",
        authorRole: "client",
        assetVersionId: "ver-poster-v1",
        pageNumber: null,
        x: null,
        y: null,
        rawText:
          "Could we try a brighter red? I want it to pop on the street. People walk past too many beige shops.",
        sourceLabel: "Review comment",
        createdAt: T.c3,
      },
      {
        id: "src-4",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "general_comment",
        authorName: "Maya Chen",
        authorRole: "client",
        assetVersionId: null,
        pageNumber: null,
        x: null,
        y: null,
        rawText:
          "Please keep the approved neutral palette — cream, umber, charcoal. No bright red. That's a hard no from brand. We already decided this.",
        sourceLabel: "Review comment",
        createdAt: T.c4,
      },
      {
        id: "src-5",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "general_comment",
        authorName: "Priya Shah",
        authorRole: "client",
        assetVersionId: "ver-social-01",
        pageNumber: null,
        x: null,
        y: null,
        rawText:
          "Could you also make animated story versions for Instagram and TikTok? We'll need them for opening week.",
        sourceLabel: "Review comment",
        createdAt: T.c5,
      },
      {
        id: "src-6",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "pin_comment",
        authorName: "Maya Chen",
        authorRole: "client",
        assetVersionId: "ver-menu-v1",
        pageNumber: 1,
        x: 0.5,
        y: 0.16,
        rawText: "The menu headline is a little hard to read. Can we bump contrast?",
        sourceLabel: "Pin on menu",
        createdAt: T.c6,
      },
      {
        id: "src-7",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        sourceType: "general_comment",
        authorName: "Tom Walsh",
        authorRole: "client",
        assetVersionId: "ver-poster-v1",
        pageNumber: null,
        x: null,
        y: null,
        rawText: "The cup photography on the poster is beautiful. Don't lose that.",
        sourceLabel: "Review comment",
        createdAt: T.c7,
      },
    ],
    feedback: [
      {
        id: "fb-1",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "approval_signal",
        summary: "Take Concept B (serif steam lockup) forward as the identity.",
        deliverableId: "del-identity",
        assetVersionId: "ver-identity-b",
        status: "proposed",
        conflictType: "none",
        scopeSignal: "in_scope",
        confidence: 0.94,
        clarifyingQuestion: null,
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-1",
            excerpt: "We like concept B. The serif feels like us",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-2",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "request",
        summary: "Make the poster type feel warmer, without becoming childish.",
        deliverableId: "del-poster",
        assetVersionId: "ver-poster-v1",
        status: "proposed",
        conflictType: "ambiguous",
        scopeSignal: "in_scope",
        confidence: 0.62,
        clarifyingQuestion:
          "By warmer, do you mean a slightly rounder serif, a creamier paper ground, or softer ink (umber instead of charcoal)?",
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-2",
            excerpt: "Can it feel warmer but not childish? The type is a little severe",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-3",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "request",
        summary: "Introduce a brighter red so the poster ‘pops’ on the street.",
        deliverableId: "del-poster",
        assetVersionId: "ver-poster-v1",
        status: "proposed",
        conflictType: "decision_conflict",
        scopeSignal: "in_scope",
        confidence: 0.9,
        clarifyingQuestion:
          "This reopens the accepted neutral-palette decision. Confirm with Maya before treating it as a change.",
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-3",
            excerpt: "Could we try a brighter red? I want it to pop on the street",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-4",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "observation",
        summary: "Keep the approved neutral palette. No bright red.",
        deliverableId: null,
        assetVersionId: null,
        status: "proposed",
        conflictType: "inter_feedback",
        scopeSignal: "in_scope",
        confidence: 0.96,
        clarifyingQuestion: null,
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-4",
            excerpt: "Please keep the approved neutral palette — cream, umber, charcoal. No bright red",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-5",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "request",
        summary: "Add animated Instagram/TikTok story versions for opening week.",
        deliverableId: "del-social",
        assetVersionId: "ver-social-01",
        status: "proposed",
        conflictType: "potential_scope",
        scopeSignal: "potential_change",
        confidence: 0.88,
        clarifyingQuestion:
          "Motion is listed as out of scope. Treat as a change-order candidate, not a round-2 revision.",
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-5",
            excerpt: "Could you also make animated story versions for Instagram and TikTok?",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-6",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "request",
        summary: "Increase contrast on the menu cover headline.",
        deliverableId: "del-menu",
        assetVersionId: "ver-menu-v1",
        status: "proposed",
        conflictType: "none",
        scopeSignal: "in_scope",
        confidence: 0.91,
        clarifyingQuestion: null,
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-6",
            excerpt: "The menu headline is a little hard to read. Can we bump contrast?",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
      {
        id: "fb-7",
        projectId: "project-kumo",
        reviewRoundId: "round-kumo-1",
        type: "praise",
        summary: "Keep the cup photography on the poster.",
        deliverableId: "del-poster",
        assetVersionId: "ver-poster-v1",
        status: "proposed",
        conflictType: "none",
        scopeSignal: "in_scope",
        confidence: 0.93,
        clarifyingQuestion: null,
        createdBy: "ai",
        evidence: [
          {
            sourceId: "src-7",
            excerpt: "The cup photography on the poster is beautiful. Don't lose that",
          },
        ],
        verifiedBy: null,
        verifiedAt: null,
        rejectReason: null,
      },
    ],
    changeSets: [],
    changeItems: [],
    decisions: [
      {
        id: "dec-palette",
        clientId: "client-kumo",
        projectId: "project-kumo",
        deliverableId: null,
        statement:
          "Kumo uses a neutral palette only: cream, umber, charcoal, muted sage. Bright red and high-chroma accents are out.",
        rationale:
          "The brief and Creative Contract treat quiet warmth as the brand. Street ‘pop’ via red would reopen the thesis.",
        state: "accepted",
        scope: "client",
        confirmedBy: "Avery Lin",
        confirmedAt: T.contract,
        sourceLabel: "Creative Contract v1",
        supersedesId: null,
      },
      {
        id: "dec-cliche",
        clientId: "client-kumo",
        projectId: "project-kumo",
        deliverableId: null,
        statement:
          "Do not use generic Japanese clichés, anime, or rustic cafe tropes.",
        rationale: "Kumo is contemporary and local, not a theme.",
        state: "accepted",
        scope: "project",
        confirmedBy: "Avery Lin",
        confirmedAt: T.contract,
        sourceLabel: "Creative Contract v1 — avoid list",
        supersedesId: null,
      },
      {
        id: "dec-motion",
        clientId: "client-kumo",
        projectId: "project-kumo",
        deliverableId: "del-social",
        statement: "Motion and animated stories are out of scope for the brand launch.",
        rationale: "Two revision rounds cover static identity, poster, social templates, and menu cover.",
        state: "accepted",
        scope: "project",
        confirmedBy: "Avery Lin",
        confirmedAt: T.contract,
        sourceLabel: "Creative Contract v1 — out of scope",
        supersedesId: null,
      },
      {
        id: "dec-solstice-foil",
        clientId: "client-solstice",
        projectId: "project-solstice",
        deliverableId: "del-solstice-pack",
        statement: "No gold foil. Uncoated stock only.",
        rationale: "Mineral, daylight direction. Foil read as spa-generic in round 1.",
        state: "accepted",
        scope: "client",
        confirmedBy: "Sam Okonkwo",
        confirmedAt: "2026-07-18T14:00:00.000Z",
        sourceLabel: "Round 1 change set",
        supersedesId: null,
      },
    ],
    approvals: [
      {
        id: "ap-solstice-1",
        projectId: "project-solstice",
        reviewRoundId: "round-solstice-2",
        reviewItemId: "ri-solstice",
        assetVersionId: "ver-solstice-v2",
        deliverableId: "del-solstice-pack",
        decision: "approved",
        approverName: "Jonah Reed",
        approverEmail: "jonah@solsticegoods.com",
        conditions: null,
        decidedAt: T.solsticeDone,
      },
    ],
    manifests: [
      {
        id: "man-solstice",
        projectId: "project-solstice",
        versionNumber: 1,
        state: "published",
        publishedAt: T.solsticeDone,
        acknowledgedAt: "2026-08-09T11:00:00.000Z",
        guestToken: "solstice-d1",
        notes: "Print-ready dielines and approved PNG renditions.",
      },
    ],
    deliveryItems: [
      {
        id: "di-solstice-1",
        manifestId: "man-solstice",
        deliverableId: "del-solstice-pack",
        assetVersionId: "ver-solstice-v2",
        fileLabel: "solstice-packaging-v2.png",
        usageNotes: "Approved for print. Do not recolor.",
      },
    ],
    activity: [
      {
        id: "act-1",
        projectId: "project-kumo",
        actor: "Avery Lin",
        eventType: "contract.approved",
        summary: "Approved Creative Contract v1",
        occurredAt: T.contract,
      },
      {
        id: "act-2",
        projectId: "project-kumo",
        actor: "Avery Lin",
        eventType: "review.published",
        summary: "Published Round 1 — direction",
        occurredAt: T.published,
      },
      {
        id: "act-3",
        projectId: "project-kumo",
        actor: "Maya Chen",
        eventType: "review.feedback_received",
        summary: "Maya, Tom, and Priya left round 1 comments",
        occurredAt: T.c1,
      },
    ],
    memory: [
      {
        id: "mem-1",
        clientId: "client-kumo",
        projectId: "project-kumo",
        kind: "constraint",
        statement: "Neutral palette only. No bright red.",
        status: "current",
        sourceLabel: "Brand launch · Decision",
      },
      {
        id: "mem-2",
        clientId: "client-kumo",
        projectId: "project-kumo",
        kind: "creative_principle",
        statement: "Quiet, warm, precise, contemporary. Morning light on linen.",
        status: "current",
        sourceLabel: "Brand launch · Contract",
      },
      {
        id: "mem-3",
        clientId: "client-solstice",
        projectId: "project-solstice",
        kind: "constraint",
        statement: "No gold foil. Uncoated stock only.",
        status: "current",
        sourceLabel: "Packaging system · Decision",
      },
    ],
  };
}
