/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppDecisionsRouteImport } from './routes/app/decisions'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppReviewsRouteImport } from './routes/app/reviews'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients.index'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients.$clientId'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects.$projectId'
import { Route as AppProjectsNewRouteImport } from './routes/app/projects.new'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects.$projectId.index'
import { Route as AppProjectsProjectIdDecisionsRouteImport } from './routes/app/projects.$projectId.decisions'
import { Route as AppProjectsProjectIdDeliverablesRouteImport } from './routes/app/projects.$projectId.deliverables'
import { Route as AppProjectsProjectIdDeliveryRouteImport } from './routes/app/projects.$projectId.delivery'
import { Route as AppProjectsProjectIdDirectionRouteImport } from './routes/app/projects.$projectId.direction'
import { Route as AppProjectsProjectIdReviewsRouteImport } from './routes/app/projects.$projectId.reviews'
import { Route as AppProjectsProjectIdReviewsIndexRouteImport } from './routes/app/projects.$projectId.reviews.index'
import { Route as AppProjectsProjectIdReviewsRoundIdRouteImport } from './routes/app/projects.$projectId.reviews.$roundId'
import { Route as AppProjectsProjectIdReviewsRoundIdChangesetRouteImport } from './routes/app/projects.$projectId.reviews.$roundId.changeset'
import { Route as AppProjectsProjectIdReviewsRoundIdInboxRouteImport } from './routes/app/projects.$projectId.reviews.$roundId.inbox'
import { Route as AppProjectsProjectIdReviewsRoundIdSynthesisRouteImport } from './routes/app/projects.$projectId.reviews.$roundId.synthesis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDecisionsRoute =
  AppProjectsProjectIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDeliverablesRoute =
  AppProjectsProjectIdDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDeliveryRoute =
  AppProjectsProjectIdDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDirectionRoute =
  AppProjectsProjectIdDirectionRouteImport.update({
    id: '/direction',
    path: '/direction',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdReviewsRoute =
  AppProjectsProjectIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdReviewsIndexRoute =
  AppProjectsProjectIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdReviewsRoute,
  } as any)
const AppProjectsProjectIdReviewsRoundIdRoute =
  AppProjectsProjectIdReviewsRoundIdRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => AppProjectsProjectIdReviewsRoute,
  } as any)
const AppProjectsProjectIdReviewsRoundIdChangesetRoute =
  AppProjectsProjectIdReviewsRoundIdChangesetRouteImport.update({
    id: '/changeset',
    path: '/changeset',
    getParentRoute: () => AppProjectsProjectIdReviewsRoundIdRoute,
  } as any)
const AppProjectsProjectIdReviewsRoundIdInboxRoute =
  AppProjectsProjectIdReviewsRoundIdInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AppProjectsProjectIdReviewsRoundIdRoute,
  } as any)
const AppProjectsProjectIdReviewsRoundIdSynthesisRoute =
  AppProjectsProjectIdReviewsRoundIdSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => AppProjectsProjectIdReviewsRoundIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/decisions': typeof AppDecisionsRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/app/projects/$projectId/deliverables': typeof AppProjectsProjectIdDeliverablesRoute
  '/app/projects/$projectId/delivery': typeof AppProjectsProjectIdDeliveryRoute
  '/app/projects/$projectId/direction': typeof AppProjectsProjectIdDirectionRoute
  '/app/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsRouteWithChildren
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/reviews/$roundId': typeof AppProjectsProjectIdReviewsRoundIdRouteWithChildren
  '/app/projects/$projectId/reviews/': typeof AppProjectsProjectIdReviewsIndexRoute
  '/app/projects/$projectId/reviews/$roundId/changeset': typeof AppProjectsProjectIdReviewsRoundIdChangesetRoute
  '/app/projects/$projectId/reviews/$roundId/inbox': typeof AppProjectsProjectIdReviewsRoundIdInboxRoute
  '/app/projects/$projectId/reviews/$roundId/synthesis': typeof AppProjectsProjectIdReviewsRoundIdSynthesisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/app/projects/$projectId/deliverables': typeof AppProjectsProjectIdDeliverablesRoute
  '/app/projects/$projectId/delivery': typeof AppProjectsProjectIdDeliveryRoute
  '/app/projects/$projectId/direction': typeof AppProjectsProjectIdDirectionRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/reviews/$roundId': typeof AppProjectsProjectIdReviewsRoundIdRouteWithChildren
  '/app/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsIndexRoute
  '/app/projects/$projectId/reviews/$roundId/changeset': typeof AppProjectsProjectIdReviewsRoundIdChangesetRoute
  '/app/projects/$projectId/reviews/$roundId/inbox': typeof AppProjectsProjectIdReviewsRoundIdInboxRoute
  '/app/projects/$projectId/reviews/$roundId/synthesis': typeof AppProjectsProjectIdReviewsRoundIdSynthesisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/decisions': typeof AppDecisionsRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reviews': typeof AppReviewsRoute
  '/app/settings': typeof AppSettingsRoute
  '/d/$token': typeof DTokenRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/app/projects/$projectId/deliverables': typeof AppProjectsProjectIdDeliverablesRoute
  '/app/projects/$projectId/delivery': typeof AppProjectsProjectIdDeliveryRoute
  '/app/projects/$projectId/direction': typeof AppProjectsProjectIdDirectionRoute
  '/app/projects/$projectId/reviews': typeof AppProjectsProjectIdReviewsRouteWithChildren
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/reviews/$roundId': typeof AppProjectsProjectIdReviewsRoundIdRouteWithChildren
  '/app/projects/$projectId/reviews/': typeof AppProjectsProjectIdReviewsIndexRoute
  '/app/projects/$projectId/reviews/$roundId/changeset': typeof AppProjectsProjectIdReviewsRoundIdChangesetRoute
  '/app/projects/$projectId/reviews/$roundId/inbox': typeof AppProjectsProjectIdReviewsRoundIdInboxRoute
  '/app/projects/$projectId/reviews/$roundId/synthesis': typeof AppProjectsProjectIdReviewsRoundIdSynthesisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/clients'
    | '/app/decisions'
    | '/app/projects'
    | '/app/reviews'
    | '/app/settings'
    | '/d/$token'
    | '/r/$token'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/projects/'
    | '/app/projects/$projectId/decisions'
    | '/app/projects/$projectId/deliverables'
    | '/app/projects/$projectId/delivery'
    | '/app/projects/$projectId/direction'
    | '/app/projects/$projectId/reviews'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/reviews/$roundId'
    | '/app/projects/$projectId/reviews/'
    | '/app/projects/$projectId/reviews/$roundId/changeset'
    | '/app/projects/$projectId/reviews/$roundId/inbox'
    | '/app/projects/$projectId/reviews/$roundId/synthesis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/decisions'
    | '/app/reviews'
    | '/app/settings'
    | '/d/$token'
    | '/r/$token'
    | '/app'
    | '/app/clients/$clientId'
    | '/app/projects/new'
    | '/app/clients'
    | '/app/projects'
    | '/app/projects/$projectId/decisions'
    | '/app/projects/$projectId/deliverables'
    | '/app/projects/$projectId/delivery'
    | '/app/projects/$projectId/direction'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/reviews/$roundId'
    | '/app/projects/$projectId/reviews'
    | '/app/projects/$projectId/reviews/$roundId/changeset'
    | '/app/projects/$projectId/reviews/$roundId/inbox'
    | '/app/projects/$projectId/reviews/$roundId/synthesis'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/clients'
    | '/app/decisions'
    | '/app/projects'
    | '/app/reviews'
    | '/app/settings'
    | '/d/$token'
    | '/r/$token'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/clients/'
    | '/app/projects/'
    | '/app/projects/$projectId/decisions'
    | '/app/projects/$projectId/deliverables'
    | '/app/projects/$projectId/delivery'
    | '/app/projects/$projectId/direction'
    | '/app/projects/$projectId/reviews'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/reviews/$roundId'
    | '/app/projects/$projectId/reviews/'
    | '/app/projects/$projectId/reviews/$roundId/changeset'
    | '/app/projects/$projectId/reviews/$roundId/inbox'
    | '/app/projects/$projectId/reviews/$roundId/synthesis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DTokenRoute: typeof DTokenRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/decisions': {
      id: '/app/projects/$projectId/decisions'
      path: '/decisions'
      fullPath: '/app/projects/$projectId/decisions'
      preLoaderRoute: typeof AppProjectsProjectIdDecisionsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/deliverables': {
      id: '/app/projects/$projectId/deliverables'
      path: '/deliverables'
      fullPath: '/app/projects/$projectId/deliverables'
      preLoaderRoute: typeof AppProjectsProjectIdDeliverablesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/delivery': {
      id: '/app/projects/$projectId/delivery'
      path: '/delivery'
      fullPath: '/app/projects/$projectId/delivery'
      preLoaderRoute: typeof AppProjectsProjectIdDeliveryRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/direction': {
      id: '/app/projects/$projectId/direction'
      path: '/direction'
      fullPath: '/app/projects/$projectId/direction'
      preLoaderRoute: typeof AppProjectsProjectIdDirectionRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/reviews': {
      id: '/app/projects/$projectId/reviews'
      path: '/reviews'
      fullPath: '/app/projects/$projectId/reviews'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/reviews/': {
      id: '/app/projects/$projectId/reviews/'
      path: '/'
      fullPath: '/app/projects/$projectId/reviews/'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdReviewsRoute
    }
    '/app/projects/$projectId/reviews/$roundId': {
      id: '/app/projects/$projectId/reviews/$roundId'
      path: '/$roundId'
      fullPath: '/app/projects/$projectId/reviews/$roundId'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRoundIdRouteImport
      parentRoute: typeof AppProjectsProjectIdReviewsRoute
    }
    '/app/projects/$projectId/reviews/$roundId/changeset': {
      id: '/app/projects/$projectId/reviews/$roundId/changeset'
      path: '/changeset'
      fullPath: '/app/projects/$projectId/reviews/$roundId/changeset'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRoundIdChangesetRouteImport
      parentRoute: typeof AppProjectsProjectIdReviewsRoundIdRoute
    }
    '/app/projects/$projectId/reviews/$roundId/inbox': {
      id: '/app/projects/$projectId/reviews/$roundId/inbox'
      path: '/inbox'
      fullPath: '/app/projects/$projectId/reviews/$roundId/inbox'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRoundIdInboxRouteImport
      parentRoute: typeof AppProjectsProjectIdReviewsRoundIdRoute
    }
    '/app/projects/$projectId/reviews/$roundId/synthesis': {
      id: '/app/projects/$projectId/reviews/$roundId/synthesis'
      path: '/synthesis'
      fullPath: '/app/projects/$projectId/reviews/$roundId/synthesis'
      preLoaderRoute: typeof AppProjectsProjectIdReviewsRoundIdSynthesisRouteImport
      parentRoute: typeof AppProjectsProjectIdReviewsRoundIdRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppProjectsProjectIdReviewsRoundIdRouteChildren {
  AppProjectsProjectIdReviewsRoundIdChangesetRoute: typeof AppProjectsProjectIdReviewsRoundIdChangesetRoute
  AppProjectsProjectIdReviewsRoundIdInboxRoute: typeof AppProjectsProjectIdReviewsRoundIdInboxRoute
  AppProjectsProjectIdReviewsRoundIdSynthesisRoute: typeof AppProjectsProjectIdReviewsRoundIdSynthesisRoute
}

const AppProjectsProjectIdReviewsRoundIdRouteChildren: AppProjectsProjectIdReviewsRoundIdRouteChildren =
  {
    AppProjectsProjectIdReviewsRoundIdChangesetRoute:
      AppProjectsProjectIdReviewsRoundIdChangesetRoute,
    AppProjectsProjectIdReviewsRoundIdInboxRoute:
      AppProjectsProjectIdReviewsRoundIdInboxRoute,
    AppProjectsProjectIdReviewsRoundIdSynthesisRoute:
      AppProjectsProjectIdReviewsRoundIdSynthesisRoute,
  }

const AppProjectsProjectIdReviewsRoundIdRouteWithChildren =
  AppProjectsProjectIdReviewsRoundIdRoute._addFileChildren(
    AppProjectsProjectIdReviewsRoundIdRouteChildren,
  )

interface AppProjectsProjectIdReviewsRouteChildren {
  AppProjectsProjectIdReviewsRoundIdRoute: typeof AppProjectsProjectIdReviewsRoundIdRouteWithChildren
  AppProjectsProjectIdReviewsIndexRoute: typeof AppProjectsProjectIdReviewsIndexRoute
}

const AppProjectsProjectIdReviewsRouteChildren: AppProjectsProjectIdReviewsRouteChildren =
  {
    AppProjectsProjectIdReviewsRoundIdRoute:
      AppProjectsProjectIdReviewsRoundIdRouteWithChildren,
    AppProjectsProjectIdReviewsIndexRoute:
      AppProjectsProjectIdReviewsIndexRoute,
  }

const AppProjectsProjectIdReviewsRouteWithChildren =
  AppProjectsProjectIdReviewsRoute._addFileChildren(
    AppProjectsProjectIdReviewsRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdDecisionsRoute: typeof AppProjectsProjectIdDecisionsRoute
  AppProjectsProjectIdDeliverablesRoute: typeof AppProjectsProjectIdDeliverablesRoute
  AppProjectsProjectIdDeliveryRoute: typeof AppProjectsProjectIdDeliveryRoute
  AppProjectsProjectIdDirectionRoute: typeof AppProjectsProjectIdDirectionRoute
  AppProjectsProjectIdReviewsRoute: typeof AppProjectsProjectIdReviewsRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdDecisionsRoute: AppProjectsProjectIdDecisionsRoute,
  AppProjectsProjectIdDeliverablesRoute: AppProjectsProjectIdDeliverablesRoute,
  AppProjectsProjectIdDeliveryRoute: AppProjectsProjectIdDeliveryRoute,
  AppProjectsProjectIdDirectionRoute: AppProjectsProjectIdDirectionRoute,
  AppProjectsProjectIdReviewsRoute:
    AppProjectsProjectIdReviewsRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDecisionsRoute: AppDecisionsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DTokenRoute: DTokenRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
